class Mtype(enum.IntEnum): ...
ROW_TYPE: numpy.dtype = ...
def midifile_load(filename) -> FluidMidi: ...
def midifile_save_1(midi: FluidMidi, fname: str) -> None: ...
def midifile_save_0(midi: FluidMidi, fname: str) -> None: ...
class FluidMidi:
    def make() -> FluidMidi: ...
    def print() -> None: ...
    @property
    def size() -> int: ...
    def __getitem__(self, key): ...
    def __add__(self, other: FluidMidi): ...
    def __or__(self, other: FluidMidi): ...
    def __mul__(self, other: int): ...
def tick2second(tick: int, tempo: int) -> float: ...
def second2tick(sec: float, tempo: int) -> int: ...
def bpm2tempo(bpm: float) -> int: ...
def tempo2bpm(tempo: int) -> float: ...
class FluidNode: ...
class TrackName: ...
class ControlChannelVolume: ...
class ControlBalance: ...
class OmniOn: ...
class OmniOff: ...
class PolyOn: ...
class MonoOn: ...
class Mtype: ...
class NoteOff: ...
class NoteOn: ...
class ControlChange: ...
class ProgramChange: ...
class PitchBend: ...
class TempoSet: ...
class TimeSignature: ...
class Text: ...
class TrackName: ...

class FluidMidi:
    def __init__(selfm arg, **colvals): ...
    def make(self): ...
    def size(self): ...
    def print(self, debug=False): ...
    def __getitem__(self, idx): ...
    def __add__(self, other: FluidMidi): ...
    def __or___(self, other: FluidMidi): ...
    def __mul__(self, other: FluidMidi): ...

class FluidNode:
    def append(self, child): ...

class ControlBankSelect: ...
class ControlModulationWheel: ...
class ControlBreathController: ...
class ControlFootController: ...
class ControlPortamentoTime: ...
class ControlDataEntry: ...
class ControlChannelVolume: ...
class ControlBalance: ...
class ControlPan: ...
class ControlExpressionController: ...
class ControlEffect1: ...
class ControlEffect2: ...
class SwitchSustain: ...
class SwitchPortamento: ...
class SwitchSostenuto: ...
class SwitchSoftPedal: ...
class SwitchLegato: ...
class SwitchHold2: ...
class ControlDataIncrement: ...
class ControlDataDecrement: ...
class ControlRPNSelect: ...
class RPNSelectPitchBendSensitivity: ...
class RPNSelectChannelFineTuning: ...
class RPNSelectChannelCoarseTuning: ...
class RPNSelectTuningProgram: ...
class RPNSelectTuningBank: ...
class RPNSelectModulationDepthRange: ...
class RPNNullFunction: ...
class AllSoundOff: ...
class ResetAllControllers: ...
class SwitchLocalControl: ...
class AllNotesOff: ...
class OmniOff: ...
class OmniOn: ...
class MonoOn: ...
class PolyOn: ...
class BankProgram: ...
