const char* program_changes[] = {
    "Acoustic Grand Piano",
    "Bright Acoustic Piano",
    "Electric Grand Piano",
    "Honky-tonk Piano",
    "Electric Piano 1",
    "Electric Piano 2",
    "Harpsichord",
    "Clavi",
    "Celesta",
    "Glockenspiel",
    "Music Box",
    "Vibraphone",
    "Marimba",
    "Xylophone",
    "Tubular Bells",
    "Dulcimer",
    "Drawbar Organ",
    "Percussive Organ",
    "Rock Organ",
    "Church Organ",
    "Reed Organ",
    "Accordion",
    "Harmonica",
    "Tango Accordion",
    "Acoustic Guitar (nylon)",
    "Acoustic Guitar (steel)",
    "Electric Guitar (jazz)",
    "Electric Guitar (clean)",
    "Electric Guitar (muted)",
    "Overdriven Guitar",
    "Distortion Guitar",
    "Guitar harmonics",
    "Acoustic Bass",
    "Electric Bass (finger)",
    "Electric Bass (pick)",
    "Fretless Bass",
    "Slap Bass 1",
    "Slap Bass 2",
    "Synth Bass 1",
    "Synth Bass 2",
    "Violin",
    "Viola",
    "Cello",
    "Contrabass",
    "Tremolo Strings",
    "Pizzicato Strings",
    "Orchestral Harp",
    "Timpani",
    "String Ensemble 1",
    "String Ensemble 2",
    "SynthStrings 1",
    "SynthStrings 2",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Voice",
    "Orchestra Hit",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Muted Trumpet",
    "French Horn",
    "Brass Section",
    "SynthBrass 1",
    "SynthBrass 2",
    "Soprano Sax",
    "Alto Sax",
    "Tenor Sax",
    "Baritone Sax",
    "Oboe",
    "English Horn",
    "Bassoon",
    "Clarinet",
    "Piccolo",
    "Flute",
    "Recorder",
    "Pan Flute",
    "Blown Bottle",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Lead 1 (square)",
    "Lead 2 (sawtooth)",
    "Lead 3 (calliope)",
    "Lead 4 (chiff)",
    "Lead 5 (charang)",
    "Lead 6 (voice)",
    "Lead 7 (fifths)",
    "Lead 8 (bass + lead)",
    "Pad 1 (new age)",
    "Pad 2 (warm)",
    "Pad 3 (polysynth)",
    "Pad 4 (choir)",
    "Pad 5 (bowed)",
    "Pad 6 (metallic)",
    "Pad 7 (halo)",
    "Pad 8 (sweep)",
    "FX 1 (rain)",
    "FX 2 (soundtrack)",
    "FX 3 (crystal)",
    "FX 4 (atmosphere)",
    "FX 5 (brightness)",
    "FX 6 (goblins)",
    "FX 7 (echoes)",
    "FX 8 (sci-fi)",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Kalimba",
    "Bag pipe",
    "Fiddle",
    "Shanai",
    "Tinkle Bell",
    "Agogo",
    "Steel Drums",
    "Woodblock",
    "Taiko Drum",
    "Melodic Tom",
    "Synth Drum",
    "Reverse Cymbal",
    "Guitar Fret Noise",
    "Breath Noise",
    "Seashore",
    "Bird Tweet",
    "Telephone Ring",
    "Helicopter",
    "Applause",
    "Gunshot",
};

const char* control_changes[] = {
    "Bank Select",
    "Mod. Wheel",
    "Breath Controller",
    "Undefined",
    "Foot Controller",
    "Portamento Time",
    "Data Entry MSB",
    "Channel Volume",
    "Balance",
    "Undefined",
    "Pan",
    "Expression Controller",
    "Effect Control 1",
    "Effect Control 2",
    "Undefined",
    "Undefined",
    "Gen Controller 1",
    "Gen Controller 2",
    "Gen Controller 3",
    "Gen Controller 4",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "LSB (Bank Select)",
    "LSB (Modulation Wheel)",
    "LSB (Breath Controller)",
    "LSB (Undefined)",
    "LSB (Foot Controller)",
    "LSB (Portamento Time)",
    "LSB (Data Entry)",
    "LSB (Channel Volume, formerly Main Volume)",
    "LSB (Balance)",
    "LSB (Undefined)",
    "LSB (Pan)",
    "LSB (Expression Controller)",
    "LSB (Effect control 1)",
    "LSB for Control 13 (Effect control 2)",
    "LSB for Control 14 (Undefined)",
    "LSB for Control 15 (Undefined)",
    "LSB for Control 16 (General Purpose Controller 1)",
    "LSB for Control 17 (General Purpose Controller 2)",
    "LSB for Control 18 (General Purpose Controller 3)",
    "LSB for Control 19 (General Purpose Controller 4)",
    "LSB for Control 20 (Undefined)",
    "LSB for Control 21 (Undefined)",
    "LSB for Control 22 (Undefined)",
    "LSB for Control 23 (Undefined)",
    "LSB for Control 24 (Undefined)",
    "LSB for Control 25 (Undefined)",
    "LSB for Control 26 (Undefined)",
    "LSB for Control 27 (Undefined)",
    "LSB for Control 28 (Undefined)",
    "LSB for Control 29 (Undefined)",
    "LSB for Control 30 (Undefined)",
    "LSB for Control 31 (Undefined)",
    "Damper Pedal on/off (Sustain)",
    "Portamento On/Off",
    "Sostenuto On/Off",
    "Soft Pedal On/Off",
    "Legato Footswitch",
    "Hold 2",
    "Sound Controller 1 (default: Sound Variation)",
    "Sound Controller 2 (default: Timbre/Harmonic Intens.)",
    "Sound Controller 3 (default: Release Time)",
    "Sound Controller 4 (default: Attack Time)",
    "Sound Controller 5 (default: Brightness)",
    "Sound Controller 6 (default: Decay Time - see MMA RP-021)",
    "Sound Controller 7 (default: Vibrato Rate - see MMA RP-021)",
    "Sound Controller 8 (default: Vibrato Depth - see MMA RP-021)",
    "Sound Controller 9 (default: Vibrato Delay - see MMA RP-021)",
    "Sound Controller 10 (default undefined - see MMA RP-021)",
    "General Purpose Controller 5",
    "General Purpose Controller 6",
    "General Purpose Controller 7",
    "General Purpose Controller 8",
    "Portamento Control",
    "Undefined",
    "Undefined",
    "Undefined",
    "High Resolution Velocity Prefix",
    "Undefined",
    "Undefined",
    "Eff1 (Reverb)",
    "Eff2 (Tremolo)",
    "Eff3 (Chorus)",
    "Eff4 (Celeste [Detune])",
    "Eff5 (Phaser)",
    "Data Increment (Data Entry +1) (see MMA RP-018)",
    "Data Decrement (Data Entry -1) (see MMA RP-018)",
    "Non-Registered Parameter Number (NRPN) - LSB",
    "Non-Registered Parameter Number (NRPN) - MSB",
    "Regd Param No. (RPN) - LSB*",
    "Regd Param No. (RPN) - MSB*",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "[Channel Mode Message] All Sound Off",
    "[Channel Mode Message] Reset All Controllers",
    "[Channel Mode Message] Local Control On/Off",
    "[Channel Mode Message] All Notes Off",
    "[Channel Mode Message] Omni Mode Off (+ all notes off)",
    "[Channel Mode Message] Omni Mode On (+ all notes off)",
    "[Channel Mode Message] Mono Mode On (+ poly off, + all notes off)",
    "[Channel Mode Message] Poly Mode On (+ mono off, +all notes off)",
};
